### ISSUE TITLE
Brightcove Smart Player for HTML5 video

### ISSUE THREAD

**Issue by amscotti** [NYPL/popcorn-js-brightcove-player#1]
Hi,

I been playing around with your Brightcove player plugin and it works really well on the desktop with Flash. I'm looking for something that is able to use the Brightcove Smart Player to be able to do HTML5 video also. This would be great for an upcoming project that I'm working on and I think over all would be nice for anyone else that is using the plugin that needs to target platforms without flash, like the iPad.

I played around with the code a bit to get the Smart Player embedded but I can't seem for the life of me to get the events working again. The code currently runs on both desktop browser and the iPad.

You can find the code in my fork of the repository under the 'smart_player' branch, here's a link https://github.com/amscotti/popcorn-js-brightcove-player/tree/smart_player

Could someone that has a bit more knowledge of the plugin take a look and see if this could be feasible. 

Anything I can do to help, let me know. Thanks!

**Comment by mszyndel** [comment]
@nypl
